### ISSUE TITLE
[todo] Add rooms support

### ISSUE THREAD

**Issue by a-komarev** [secusu/secusu#17]
- [x] Room hash generating automatically on create room command.
- [x] Guest can join to rooms by their hash and password.
- [x] Client can send messages to room.
- [x] #18 Private websocket rooms
- [x] Clients can see each member in the room.
- [x] Clients can recieve messages inside in the room if authorized.
- [x] Client browser ignores self-initiated websocket messages.
- [x] If room doesn't exists - display password form which will fail all the time.
- [x] If guest user post fails to join - all authenticated room users will be notified.
- [x] #14 Design API to provide frontend integration.

**Comment by a-komarev** [comment]
All tasks are done. Production deploying in progress.
